const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'eb-ui-'));process.env.ACCOUNT_FILE=path.join(dir,'users.json');const {server,accounts}=require('../server'),{parseQuotes}=require('../superbet-parser');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});try{
 const contexts=await Promise.all([browser.newContext({viewport:{width:1440,height:1000}}),browser.newContext({viewport:{width:390,height:844}})]);const errors=[];const stamp=new Date().toISOString();
 const rows=[{id:'winner',marketId:'1',label:'Zwycięzca (z dogrywką), Boston Celtics, współczynnik 2.2, active'}];for(const [i,line]of [231.5,233.5,235.5,237.5].entries())for(const side of ['Powyżej','Poniżej'])rows.push({id:side+i,marketId:'2',label:`Liczba punktów (z dogrywką), ${side} ${line} punktów w meczu (z dogrywką), współczynnik 1.9, active`});for(const line of [1.5,3.5])for(const team of ['Boston Celtics','New York Knicks'])rows.push({id:team+line,marketId:'3',label:`Handicap (z dogrywką), ${team} (${team==='Boston Celtics'?'-':'+'}${line}), współczynnik 1.8, active`});
 const event={id:'sb1',h:'Boston Celtics',a:'New York Knicks',t:new Date(Date.now()+864e5).toISOString(),mk:parseQuotes(rows,stamp),source:'superbet',book:'Superbet',manualSettlement:true,updatedAt:stamp};
 for(const c of contexts){await c.route(/https:\/\//,r=>r.abort());await c.route('**/api/superbet',r=>r.fulfill({json:{status:'done',events:[event],completed:1,total:1,errors:[]}}));}
 const desktop=await contexts[0].newPage(),phone=await contexts[1].newPage();for(const p of [desktop,phone])p.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;
 await desktop.goto(url);await desktop.waitForFunction(()=>accountReady);assert.equal(await desktop.locator('.market-card').count(),3);assert.equal(await desktop.locator('#rem').count(),0);assert.ok(!(await desktop.locator('#oddsPanel').innerText()).includes('bez płatnego API'));assert.equal(await desktop.locator('.market-card').nth(1).locator('.market-line').count(),4);assert.equal(await desktop.locator('.market-card').nth(2).locator('.market-line').count(),2);
 await desktop.locator('#accountButton').click();await desktop.locator('[data-auth-tab="register"]').click();await desktop.locator('[name=name]').fill('David');await desktop.locator('[name=email]').fill('david@example.com');await desktop.locator('[name=password]').fill('test-password-123');await desktop.locator('#accountForm button[type=submit]').click();await desktop.waitForFunction(()=>accountUser?.name==='David');
 await desktop.locator('.od').first().click();await desktop.locator('#st').fill('100');assert.ok(await desktop.locator('#st').evaluate(e=>e.getBoundingClientRect().width<=48&&e.getBoundingClientRect().height<=26));assert.equal(await desktop.locator('.od.on').first().evaluate(e=>getComputedStyle(e).boxShadow),'none');assert.equal(await desktop.locator('[data-source]').count(),0);await desktop.locator('#place').click();await desktop.waitForFunction(()=>!accountDirty&&!accountSaving&&S.bets.length===1);assert.equal(await desktop.locator('#bal').innerText(),'900,00 zł');
 await phone.goto(url);await phone.waitForFunction(()=>accountReady);assert.equal(await phone.locator('#bal').innerText(),'1000,00 zł');await phone.locator('#accountButton').click();await phone.locator('[name=email]').fill('david@example.com');await phone.locator('[name=password]').fill('test-password-123');await phone.locator('#accountForm button[type=submit]').click();await phone.waitForFunction(()=>accountUser?.name==='David');assert.equal(await phone.locator('#bal').innerText(),'900,00 zł');await phone.getByRole('button',{name:/Moje kupony/}).click();assert.equal(await phone.locator('.cp').count(),1);await phone.locator('[data-a=won]').click();await phone.waitForFunction(()=>!accountDirty&&!accountSaving);assert.equal(await phone.locator('#bal').innerText(),'1120,00 zł');await desktop.evaluate(()=>pollAccount());await desktop.waitForFunction(()=>S.bal===1120);
 await phone.getByRole('button',{name:'Mecze',exact:true}).click();assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await desktop.getByRole('button',{name:'Mecze',exact:true}).click();if(process.env.QA_DIR){await desktop.screenshot({path:process.env.QA_DIR+'/desktop.png',fullPage:true,animations:'disabled'});await phone.screenshot({path:process.env.QA_DIR+'/mobile.png',fullPage:true,animations:'disabled'});await desktop.locator('#accountButton').click();await desktop.screenshot({path:process.env.QA_DIR+'/account.png',animations:'disabled'});}
 await desktop.locator('#accountClose').click().catch(()=>{});await desktop.route('**/api/account/state',r=>r.abort());await desktop.locator('.od').first().click();await desktop.locator('#place').click();await desktop.waitForFunction(()=>accountDirty&&!accountSaving);assert.ok((await desktop.locator('#syncStatus').innerText()).includes('Nie zapisano'));await desktop.unroute('**/api/account/state');await desktop.evaluate(()=>flushAccount());await desktop.waitForFunction(()=>!accountDirty&&!accountSaving);
 await desktop.locator('#accountButton').click();await desktop.locator('#accountLogout').click();await desktop.waitForFunction(()=>!accountUser);assert.equal(await desktop.locator('#bal').innerText(),'1000,00 zł');assert.deepEqual(errors,[]);
 console.log('UI: grouped totals/handicaps, matte/mobile layout, registration, device sync, settlement, retry and guest isolation PASS');
 }finally{await browser.close();await accounts.store.close();server.close();fs.rmSync(dir,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
