const {chromium}=require('playwright'),assert=require('node:assert/strict'),{server}=require('../server'),{parseQuotes}=require('../superbet-parser');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/https:\/\//,r=>r.abort());
 const stamp=new Date().toISOString(),t=new Date(Date.now()+864e5).toISOString();let version=1;
 const rows=()=>[{id:'main',marketId:'759',label:'Zwycięzca (z dogrywką), Boston Celtics wygra mecz (z dogrywką), współczynnik '+(version===3?'2.3':'2.2')+', active'},...(version>=2?[{id:'prop',marketId:'500',label:'Punkty zawodnika, Tatum Powyżej 25.5, współczynnik 1.9, active'}]:[])];
 const event=()=>({id:'sb123',h:'Boston Celtics',a:'New York Knicks',t,mk:parseQuotes(rows(),stamp),source:'superbet',book:'Superbet',updatedAt:stamp,manualSettlement:true});
 await page.route('**/api/superbet',r=>r.fulfill({json:{status:'done',events:[event()],errors:[],total:1,completed:1,finishedAt:stamp}}));
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('.hero').waitFor();assert.ok((await page.locator('#main').innerText()).includes('Superbet'));assert.equal(await page.locator('details.box').count(),1);
 version=2;await page.evaluate(()=>refreshSource());await page.getByText('Punkty zawodnika · Tatum',{exact:true}).waitFor();assert.equal(await page.locator('details.box').count(),2,'new props appear without opening a props request');
 await page.locator('.od').first().click();version=3;await page.evaluate(()=>refreshSource());await page.waitForFunction(()=>M[0].mk[0][1][0][1]===2.3);await page.getByRole('button',{name:'Postaw zakład',exact:true}).click();assert.ok((await page.locator('#er').innerText()).includes('zmieniła się'));assert.equal(await page.locator('#bal').innerText(),'1000,00 zł');
 await page.locator('.od').first().click();await page.locator('.od').first().click();await page.getByRole('button',{name:'Postaw zakład',exact:true}).click();assert.equal(await page.locator('#bal').innerText(),'950,00 zł');assert.equal(await page.evaluate(()=>S.bets[0].odds),2.3);
 version=1;await page.evaluate(()=>refreshSource());await page.waitForFunction(()=>M[0].mk[0][1][0][1]===2.2);assert.equal(await page.evaluate(()=>S.bets[0].odds),2.3,'placed ticket keeps its original odds');
 await page.getByRole('button',{name:'Mecze',exact:true}).click();await page.evaluate(()=>{M[0].mk[0][1][0][2].updatedAt=new Date(Date.now()-11*60e3).toISOString();render()});assert.equal(await page.locator('.od').first().isDisabled(),true);
 assert.deepEqual(errors,[]);if(process.env.QA_DIR){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:process.env.QA_DIR+'/superbet.png',fullPage:true,animations:'disabled'});}console.log('Superbet UI: automatic offers, newly published props, changed quote rejection, ticket odds and stale quote PASS');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
