const {chromium}=require('playwright'),assert=require('node:assert/strict'),{server}=require('../server');
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))requests.push(r.url());});
 await page.route(/https:\/\//,r=>r.abort());
 await page.route('**/api/superbet',r=>r.fulfill({json:{status:'done',events:[],errors:[],completed:0,total:0}}));
 const existing={id:'old',st:'open',stake:50,odds:2.12,legs:[{label:'Boston Celtics',mk:'Zwycięzca',match:'Pistons – Celtics',odds:2.12,meta:{t:'ml',team:'Boston Celtics'}}]};
 await page.addInitScript(existing=>{if(!localStorage.getItem('nbaBook1'))localStorage.setItem('nbaBook1',JSON.stringify({bal:950,bets:[existing],custom:[]}));},existing);
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('.tools-menu').evaluate(e=>e.open=true);await page.waitForFunction(()=>accountReady);assert.equal(await page.locator('#bal').innerText(),'950,00 zł');
 await page.getByRole('button',{name:/Moje kupony/}).click();assert.ok((await page.locator('#main').innerText()).includes('Boston Celtics'));assert.equal(await page.getByRole('button',{name:'Sprawdź teraz'}).count(),0);
 await page.locator('.tools-menu').evaluate(e=>e.open=true);await page.getByRole('button',{name:'+ Dodaj mecz ręcznie',exact:true}).click();await page.locator('#nh').fill('Boston Celtics');await page.locator('#na').fill('New York Knicks');await page.getByRole('button',{name:'Dodaj mecz',exact:true}).click();await page.locator('.hero').waitFor();assert.equal(await page.locator('.mc.on').evaluate(e=>getComputedStyle(e).borderTopWidth),'2px');
 async function add(kind,name,person,pick,price){await page.locator('#rk').selectOption({label:kind});await page.locator('#rn').fill(name);await page.locator('#rp').fill(person);await page.locator('#ro').fill(pick);await page.locator('#rc').fill(String(price));await page.locator('[data-market]').click();}
 await add('Zawodnik','PRA 35.5','Jayson Tatum','Powyżej 35.5',2.2);await add('Zawodnik','PRA 35.5','Jayson Tatum','Poniżej 35.5',1.8);assert.equal(await page.locator('.market-card').count(),1);
 if(!await page.locator('.market-card').first().evaluate(e=>e.open))await page.locator('.market-card summary').click();await page.getByRole('button',{name:/Powyżej 35.5/}).click();assert.ok((await page.locator('#slip').innerText()).includes('2,20'));await page.getByRole('button',{name:/Poniżej 35.5/}).click();assert.equal(await page.locator('#slip .leg').count(),1);assert.ok((await page.locator('#slip').innerText()).includes('1,80'));
 await page.getByRole('button',{name:'Postaw zakład',exact:true}).click();assert.equal(await page.locator('#bal').innerText(),'900,00 zł');await page.locator('[data-a="won"]').first().click();assert.equal(await page.locator('#bal').innerText(),'990,00 zł');await page.locator('[data-a="undo"]').first().click();assert.equal(await page.locator('#bal').innerText(),'900,00 zł');
 await page.getByRole('button',{name:'Mecze',exact:true}).click();await add('1. kwarta','Suma punktów 50.5','','Powyżej 50.5',2);assert.equal(await page.locator('.market-card').count(),2);
 await page.evaluate(()=>scrollTo(0,0));if(process.env.QA_DIR)await page.screenshot({path:process.env.QA_DIR+'/offline.png',fullPage:true,animations:'disabled'});
 await page.reload();await page.locator('.hero').waitFor();assert.equal(await page.locator('.market-card').count(),2);assert.equal(await page.locator('#bal').innerText(),'900,00 zł');
 await page.locator('.tools-menu').evaluate(e=>e.open=true);await page.getByRole('button',{name:'+ Dodaj mecz ręcznie',exact:true}).click();await page.locator('#nseason').selectOption('preseason');await page.locator('#nh').fill('Chicago Bulls');await page.locator('#na').fill('Miami Heat');await page.getByRole('button',{name:'Dodaj mecz',exact:true}).click();assert.equal(await page.locator('.mc.on .badge-pre').innerText(),'PRESEASON');assert.equal(await page.locator('[data-cat="preseason"]').innerText(),'Preseason (1)');
 const imported={matches:[{id:'fixture-import',h:'A Team',a:'B Team',t:'2030-01-01T20:00:00Z',mk:[['Dowolny rynek',[['Tak',2.5]]]]}]};
 page.once('dialog',d=>d.accept());await page.locator('#offlineImport').setInputFiles({name:'matches.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.getByText('Dowolny rynek',{exact:true}).waitFor();
 const download=page.waitForEvent('download');await page.locator('[data-export]').click();assert.equal((await download).suggestedFilename(),'easybet-mecze.json');
 const prior=await page.evaluate(()=>S.custom.length);page.once('dialog',d=>d.accept());await page.locator('#offlineImport').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({matches:[{...imported.matches[0],mk:[['Bad',[['No',0]]]]}]}))});assert.equal(await page.evaluate(()=>S.custom.length),prior);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(process.env.QA_DIR)await page.screenshot({path:process.env.QA_DIR+'/mobile.png',fullPage:true,animations:'disabled'});
 assert.ok(requests.every(u=>['/api/superbet','/api/account/me','/api/results'].includes(new URL(u).pathname)));assert.deepEqual(errors,[]);console.log('UI: offline, no API, saved coupons, manual props, grouping, settlement, reload, Preseason, import/export and mobile PASS');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
